
name: Scan for secrets

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    - name: Dogfood
      uses: ./
      id: dogfood
      with:
        extra_args: --results=verified,unknown
